# Generated by Django 5.1.4 on 2025-12-26 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaAmbulatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('motivo_consulta', models.TextField(blank=True)),
                ('anamnesis', models.TextField(blank=True)),
                ('examen_fisico', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('intervenciones', models.TextField(blank=True)),
                ('factores', models.TextField(blank=True)),
                ('rau_necesidades', models.TextField(blank=True)),
                ('instrumentos_aplicados', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_creadas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_modificadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_ambulatorias', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Ficha Ambulatoria',
                'verbose_name_plural': 'Fichas Ambulatorias',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
