# Generated by Django 5.1.4 on 2026-03-21 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0003_prevision_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_plantilla', models.BooleanField(default=False, help_text='True si es la ficha base creada por docente')),
                ('contenido', models.JSONField(blank=True, default=dict, help_text='Campos clínicos de la ficha en formato JSON')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_creadas', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(blank=True, help_text='Estudiante dueño de esta ficha (null si es plantilla)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_como_estudiante', to=settings.AUTH_USER_MODEL)),
                ('ficha_base', models.ForeignKey(blank=True, help_text='Ficha plantilla de la cual se originó esta ficha de estudiante', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fichas_estudiantes', to='fichas.ficha')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_modificadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Ficha',
                'verbose_name_plural': 'Fichas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='FichaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('rol_autor', models.CharField(blank=True, default='', help_text='Rol con el que actuó el autor (ESTUDIANTE, DOCENTE, etc.)', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.JSONField(blank=True, default=dict, help_text='Snapshot del contenido clínico en esta versión')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='fichas.ficha')),
            ],
            options={
                'verbose_name': 'Versión de Ficha',
                'verbose_name_plural': 'Versiones de Fichas',
                'ordering': ['-version'],
            },
        ),
        migrations.AddConstraint(
            model_name='ficha',
            constraint=models.UniqueConstraint(condition=models.Q(('estudiante__isnull', False)), fields=('ficha_base', 'estudiante'), name='unique_estudiante_por_ficha_base'),
        ),
        migrations.AddConstraint(
            model_name='fichaversion',
            constraint=models.UniqueConstraint(fields=('ficha', 'version'), name='unique_version_por_ficha'),
        ),
    ]
