# Generated by Django 5.1.4 on 2025-12-26 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo_consulta', models.TextField(blank=True)),
                ('anamnesis', models.TextField(blank=True)),
                ('examen_fisico', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('intervenciones', models.TextField(blank=True)),
                ('factores', models.TextField(blank=True)),
                ('rau_necesidades', models.TextField(blank=True)),
                ('instrumentos_aplicados', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Historial de Ficha',
                'verbose_name_plural': 'Historial de Fichas',
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='fichaambulatoria',
            name='es_plantilla',
            field=models.BooleanField(default=False, help_text='True si es la ficha base creada por docente'),
        ),
        migrations.AddField(
            model_name='fichaambulatoria',
            name='estudiante',
            field=models.ForeignKey(blank=True, help_text='Estudiante dueño de esta ficha (null si es plantilla)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichas_como_estudiante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichaambulatoria',
            name='ficha_base',
            field=models.ForeignKey(blank=True, help_text='Ficha plantilla de la cual se originó esta ficha de estudiante', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichas_estudiantes', to='fichas.fichaambulatoria'),
        ),
        migrations.AddConstraint(
            model_name='fichaambulatoria',
            constraint=models.UniqueConstraint(condition=models.Q(('estudiante__isnull', False)), fields=('ficha_base', 'estudiante'), name='unique_estudiante_por_ficha_base'),
        ),
        migrations.AddField(
            model_name='fichahistorial',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='fichas.fichaambulatoria'),
        ),
        migrations.AddField(
            model_name='fichahistorial',
            name='modificado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='fichahistorial',
            unique_together={('ficha', 'version')},
        ),
    ]
