# Generated by Django 5.1.4 on 2026-03-29 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0004_rediseno_atencion_clinica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casoclinico',
            name='tema',
            field=models.CharField(blank=True, default='', help_text='Unidad temática o curricular', max_length=255),
        ),
        migrations.CreateModel(
            name='Vineta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Número secuencial de la viñeta dentro de esta asignación')),
                ('contenido', models.TextField(help_text='Texto narrativo de la viñeta (motivo de consulta, resultados, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('atencion_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinetas', to='fichas.atencionestudiante')),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vinetas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Viñeta',
                'verbose_name_plural': 'Viñetas',
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='evolucion',
            name='vineta',
            field=models.ForeignKey(blank=True, help_text='Viñeta a la que responde esta evolución (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evoluciones_asociadas', to='fichas.vineta'),
        ),
        migrations.AddConstraint(
            model_name='vineta',
            constraint=models.UniqueConstraint(fields=('atencion_estudiante', 'numero'), name='unique_numero_por_vineta'),
        ),
    ]
