# Generated by Django 5.1.4 on 2026-03-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0005_casoclinico_tema_vineta_evolucion_vineta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencionestudiante',
            name='entregado',
            field=models.BooleanField(default=False, help_text='Si True, el estudiante ya entregó y no puede editar sus evoluciones'),
        ),
    ]
