# Generated by Django 5.1.4 on 2026-03-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0006_atencion_estudiante_entregado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencionestudiante',
            name='entregado',
        ),
        migrations.AddField(
            model_name='evolucion',
            name='entregada',
            field=models.BooleanField(default=False, help_text='Si True, esta evolución fue entregada y no puede ser editada por el estudiante'),
        ),
    ]
