# Generated by Django 5.1.4 on 2025-12-26 03:38

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[apps.common.validators.validate_rut], verbose_name='RUT'),
        ),
    ]
