# Generated by Django 5.1.4 on 2026-03-21 00:44

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('DOCENTE', 'Docente'), ('ESTUDIANTE', 'Estudiante')], db_index=True, default='ESTUDIANTE', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[apps.common.validators.validate_rut], verbose_name='RUT'),
        ),
    ]
