# Generated by Django 5.1.4 on 2026-03-21 01:02

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_rut_unique_role_index_names_required_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[apps.common.validators.validate_rut], verbose_name='RUT'),
        ),
    ]
