# Generated by Django 5.1.4 on 2026-03-21 01:02

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(max_length=20, unique=True, validators=[apps.common.validators.validate_rut], verbose_name='RUT'),
        ),
    ]
