# Generated by Django 5.1.4 on 2026-03-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_rut_increase_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='prevision',
            field=models.CharField(choices=[('FONASA', 'FONASA'), ('ISAPRE', 'ISAPRE'), ('PARTICULAR', 'PARTICULAR')], max_length=20),
        ),
    ]
