# Generated by Django 5.1.4 on 2026-03-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_prevision_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='alergias',
            field=models.TextField(blank=True, default='', help_text='Alergias conocidas'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='antecedentes_personales',
            field=models.TextField(blank=True, default='', help_text='Antecedentes médicos del paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medicamentos_habituales',
            field=models.TextField(blank=True, default='', help_text='Medicamentos de uso habitual'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('OTRO', 'Otro'), ('NO_INFORMA', 'No informa')], default='NO_INFORMA', max_length=20),
        ),
    ]
